export const PAINTINGS = [
  {
    id: 1,
    name: "Delphyne",
    src: "./src/images/1.jpeg",
    descr: "Oil on canvas, 2019",
    size: "90 x 70 cm",
    className: "painting-1",
  },
  {
    id: 2,
    name: "Raw Life Livin'",
    src: "./src/images/2.jpeg",
    descr: "Oil on canvas, 2021",
    size: "90 x 70 cm",
    className: "painting-2",
  },
  {
    id: 3,
    name: "Dragon 2",
    src: "./src/images/3.png",
    descr: "Oil on canvas, 2021",
    size: "120 x 100 cm",
    className: "painting-3",
  },
  {
    id: 4,
    name: "Dragon 1",
    src: "./src/images/4.jpg",
    descr: "Oil on canvas, 2021",
    size: "150 x 120 cm",
    className: "painting-4",
  },
  {
    id: 5,
    name: "Savage Beauty 2",
    src: "./src/images/5.jpg",
    descr: "Oil on canvas, 2021",
    size: "120 x 100 cm ",
    className: "painting-5",
  },
  {
    id: 6,
    name: "Horsemen",
    src: "./src/images/6.jpg",
    descr: "Oil on canvas, 2021",
    size: "140 x 140 cm",
    className: "painting-6",
  },
  {
    id: 7,
    name: "After Goya's Nude Maya",
    src: "./src/images/7.jpg",
    descr: "Oil on canvas, 2021",
    size: "150 x 110 cm",
    className: "painting-7",
  },
  {
    id: 8,
    name: "Agony",
    src: "./src/images/8.jpg",
    descr: "Oil on canvas, 2022",
    size: "150 x 110 cm",
    className: "painting-8",
  },
  {
    id: 9,
    name: "Raphael - Pope Leo X with two cardinals",
    src: "./src/images/9.jpg",
    descr: "Oil on canvas, 2021",
    size: "170 x 140 cm",
    className: "painting-9",
  },
  {
    id: 10,
    name: "Warrior",
    src: "./src/images/10.jpg",
    descr: "Oil on canvas, 2022",
    size: "170 x 140 cm",
    className: "painting-10",
  },
  {
    id: 11,
    name: "Fleshy Flesh",
    src: "./src/images/11.jpeg",
    descr: "Oil on canvas, 2022",
    size: "170 x 140 cm",
    className: "painting-11",
  },
  {
    id: 12,
    name: "Taxonomy",
    src: "./src/images/12.jpeg",
    descr: "Oil on canvas, 2021",
    size: "120 x 80 cm ",
    className: "painting-12",
  },
  {
    id: 13,
    name: "Explosion of Dragon",
    src: "./src/images/13.png",
    descr: "Oil on canvas, 2021",
    size: "120 x 100 cm ",
    className: "painting-13",
  },
  {
    id: 14,
    name: "After Velasquez (Pope Innocent X)",
    src: "./src/images/14.png",
    descr: "Oil on canvas, 2021",
    size: "80 x 120 cm ",
    className: "painting-14",
  },
  {
    id: 15,
    name: "Monster with fish",
    src: "./src/images/15.png",
    descr: "Oil on wood panel, 2011",
    size: "40 x 35 cm ",
    className: "painting-15",
  },
  {
    id: 16,
    name: "Bathing",
    src: "./src/images/16.png",
    descr: "Oil on canvas, 2011",
    size: "70 x 50 cm ",
    className: "painting-16",
  },
  {
    id: 17,
    name: "Monster with fish 2",
    src: "./src/images/17.png",
    descr: "Oil on canvas, 2011",
    size: "200 x 150 cm ",
    className: "painting-17",
  },
  {
    id: 18,
    name: "Metaphysical Landscape",
    src: "./src/images/18.png",
    descr: "Oil on canvas, 2012",
    size: "8250 x 125 cm ",
    className: "painting-18",
  },
  {
    id: 19,
    name: "Backyard",
    src: "./src/images/19.png",
    descr: "Oil on canvas, 2013",
    size: "200 x 150 cm",
    className: "painting-19",
  },
  {
    id: 20,
    name: "After Velasquez (Pope Innocent X)",
    src: "./src/images/20.png",
    descr: "Oil on canvas, 2021",
    size: "80 x 120 cm ",
    className: "painting-20",
  },
  {
    id: 21,
    name: "After Velasquez (Pope Innocent X)",
    src: "./src/images/21.png",
    descr: "Oil on canvas, 2021",
    size: "80 x 120 cm ",
    className: "painting-21",
  },
  {
    id: 22,
    name: "After Velasquez (Pope Innocent X)",
    src: "./src/images/22.png",
    descr: "Oil on canvas, 2021",
    size: "80 x 120 cm ",
    className: "painting-22",
  },
  {
    id: 23,
    name: "After Velasquez (Pope Innocent X)",
    src: "./src/images/23.png",
    descr: "Oil on canvas, 2021",
    size: "80 x 120 cm ",
    className: "painting-23",
  },
  {
    id: 24,
    name: "After Velasquez (Pope Innocent X)",
    src: "./src/images/24.png",
    descr: "Oil on canvas, 2021",
    size: "80 x 120 cm ",
    className: "painting-24",
  },
  {
    id: 25,
    name: "After Velasquez (Pope Innocent X)",
    src: "./src/images/25.png",
    descr: "Oil on canvas, 2021",
    size: "80 x 120 cm ",
    className: "painting-25",
  },
  {
    id: 26,
    name: "After Velasquez (Pope Innocent X)",
    src: "./src/images/26.png",
    descr: "Oil on canvas, 2021",
    size: "80 x 120 cm ",
    className: "painting-26",
  },
  {
    id: 27,
    name: "After Velasquez (Pope Innocent X)",
    src: "./src/images/27.png",
    descr: "Oil on canvas, 2021",
    size: "80 x 120 cm ",
    className: "painting-27",
  },
  {
    id: 28,
    name: "After Velasquez (Pope Innocent X)",
    src: "./src/images/28.png",
    descr: "Oil on canvas, 2021",
    size: "80 x 120 cm ",
    className: "painting-28",
  },
  {
    id: 29,
    name: "After Velasquez (Pope Innocent X)",
    src: "./src/images/29.png",
    descr: "Oil on canvas, 2021",
    size: "80 x 120 cm ",
    className: "painting-29",
  },
  {
    id: 30,
    name: "After Velasquez (Pope Innocent X)",
    src: "./src/images/30.png",
    descr: "Oil on canvas, 2021",
    size: "80 x 120 cm ",
    className: "painting-30",
  },
  {
    id: 31,
    name: "After Velasquez (Pope Innocent X)",
    src: "./src/images/31.png",
    descr: "Oil on canvas, 2021",
    size: "80 x 120 cm ",
    className: "painting-31",
  },
  {
    id: 32,
    name: "After Velasquez (Pope Innocent X)",
    src: "./src/images/32.png",
    descr: "Oil on canvas, 2021",
    size: "80 x 120 cm ",
    className: "painting-32",
  },
  {
    id: 33,
    name: "After Velasquez (Pope Innocent X)",
    src: "./src/images/33.png",
    descr: "Oil on canvas, 2021",
    size: "80 x 120 cm ",
    className: "painting-33",
  },
  {
    id: 34,
    name: "After Velasquez (Pope Innocent X)",
    src: "./src/images/34.png",
    descr: "Oil on canvas, 2021",
    size: "80 x 120 cm ",
    className: "painting-34",
  },
];
